global:
  cattle:
    systemDefaultRegistry: ""

aksOperator:
  image:
    repository: wangsiye/aks-operator
    tag: test2

httpProxy: ""
httpsProxy: ""
noProxy: ""
additionalTrustedCAs: false

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## List of node taints to tolerate (requires Kubernetes >= 1.6)
tolerations: []

